// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class ApplyEvent
    {
        public int ApplyEventId { get; set; }
        public int MemberId { get; set; }
        public int EventId { get; set; }
        public DateTime CreateDate { get; set; }
        public string Status { get; set; }
        public int TotalPeople { get; set; }
        public int TotalPet { get; set; }

        public virtual Event Event { get; set; }
        public virtual Member Member { get; set; }
    }
}