// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class Coupon
    {
        public Coupon()
        {
            MemberCoupons = new HashSet<MemberCoupon>();
            ProductOrders = new HashSet<ProductOrder>();
            RoomOrders = new HashSet<RoomOrder>();
        }

        public int CouponId { get; set; }
        public string DiscountCode { get; set; }
        public string DiscountName { get; set; }
        public int? Conditions { get; set; }
        public int? DiscountAmount { get; set; }
        public string UserType { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? Qty { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<MemberCoupon> MemberCoupons { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual ICollection<RoomOrder> RoomOrders { get; set; }
    }
}