// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class Event
    {
        public Event()
        {
            ApplyEvents = new HashSet<ApplyEvent>();
        }

        public int EventId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string EventsCategoryName { get; set; }
        public DateTime ApplyTimeStart { get; set; }
        public DateTime ApplyTimeEnd { get; set; }
        public DateTime ProgressTimeStart { get; set; }
        public DateTime ProgressTimeEnd { get; set; }
        public string Location { get; set; }
        public int ApplicantLimitedQty { get; set; }
        public int EventApplicantsQty { get; set; }
        public string EventInfo { get; set; }

        public virtual ICollection<ApplyEvent> ApplyEvents { get; set; }
    }
}