// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class Member
    {
        public Member()
        {
            Adoptions = new HashSet<Adoption>();
            ApplyEvents = new HashSet<ApplyEvent>();
            MemberCoupons = new HashSet<MemberCoupon>();
            MemberTags = new HashSet<MemberTag>();
            ProductOrders = new HashSet<ProductOrder>();
            RoomCartItems = new HashSet<RoomCartItem>();
            RoomOrders = new HashSet<RoomOrder>();
        }

        public int MemberId { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string EncryptedPassword { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string BirthDate { get; set; }
        public string Address { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmCode { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual ICollection<Adoption> Adoptions { get; set; }
        public virtual ICollection<ApplyEvent> ApplyEvents { get; set; }
        public virtual ICollection<MemberCoupon> MemberCoupons { get; set; }
        public virtual ICollection<MemberTag> MemberTags { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual ICollection<RoomCartItem> RoomCartItems { get; set; }
        public virtual ICollection<RoomOrder> RoomOrders { get; set; }
    }
}