// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class ParentCategory
    {
        public ParentCategory()
        {
            ChildCategories = new HashSet<ChildCategory>();
        }

        public int ParentCategoryId { get; set; }
        public string Name { get; set; }
        public int ProductCategoryId { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<ChildCategory> ChildCategories { get; set; }
    }
}