// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class ProductOrder
    {
        public ProductOrder()
        {
            ProductOrderItems = new HashSet<ProductOrderItem>();
        }

        public int ProductOrderId { get; set; }
        public int MemberId { get; set; }
        public decimal Total { get; set; }
        public string OrderStatus { get; set; }
        public string RequestRefund { get; set; }
        public DateTime? RequestRedfundTime { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public int PaymentId { get; set; }
        public string PaymentStatus { get; set; }
        public int ShipmentId { get; set; }
        public string ShipmentStatus { get; set; }
        public DateTime CreateDate { get; set; }
        public int? CouponId { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Member Member { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual ICollection<ProductOrderItem> ProductOrderItems { get; set; }
    }
}