// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class RoomOrder
    {
        public RoomOrder()
        {
            RoomOrderItems = new HashSet<RoomOrderItem>();
        }

        public int RoomOrderId { get; set; }
        public int MemberId { get; set; }
        public DateTime OrderDate { get; set; }
        public int CouponId { get; set; }
        public decimal TotalPrice { get; set; }
        public string Status { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<RoomOrderItem> RoomOrderItems { get; set; }
    }
}