// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class RoomOrderItem
    {
        public int RoomOrderItemId { get; set; }
        public int RoomOrderId { get; set; }
        public int RoomId { get; set; }
        public decimal RoomPrice { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int Days { get; set; }

        public virtual Room Room { get; set; }
        public virtual RoomOrder RoomOrder { get; set; }
    }
}