// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSite.Models.EFModels
{
    public partial class Shipment
    {
        public Shipment()
        {
            ProductOrders = new HashSet<ProductOrder>();
        }

        public int ShipmentId { get; set; }
        public string ShipmentMethod { get; set; }

        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
    }
}